services:
  postgres_food_bridge:
    container_name: postgres_fun_park
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pg_fun_park